### PR TITLE
Integrate meal plan and suggestion implementation with server

### PR DESCRIPTION
**Pull request by andrewbailey**
Makes progress towards #27 and #34. This PR covers the basics of communicating with the server to store meal plans and fetch meal suggestions. Additional work will be required to ensure that the UI is updated to show the status of asynchronous operations and network errors when modifying meal plans.

### CODE REVIEW

**Review by adurso3 — COMMENTED** [review]
Looks good for the most part, though you already know that removing from the meal plan is bugged; removing from a MealPeriod with only one meal will fail, and removing from a MealPeriod with multiple meals will duplicate the deleted meal. I'm not sure if you want to go ahead and merge this in and fix this with another PR or what.

**Comment by andrewbailey** [comment]
This should be ready for review. One thing I noticed when fixing the deletion behavior was that it takes a while between when you click the delete button and when the meal plan gets updated because network calls. It's kinda hacky, but should we just always assume we're successful and just immediately update the meal plan UI?

**Comment by adurso3** [comment]
I suppose the conservative way to do this would be keep the meal in UI until it's deleted in the backend, but I don't particularly like that idea. So yeah, I'd say go ahead and update the UI and pray that the network calls are always successful.

**Comment by andrewbailey** [comment]
And it is done. Luckily it's just a one-liner, so we can revisit this if it becomes an issue.

**Comment by adurso3** [comment]
So... I don't know what you're doing but adding a meal to the current day updates the UI but doesn't update in Firebase. I'm so good at code review.

**Comment by andrewbailey** [comment]
It's probably a server thing because timezones and it's close to midnight. This definitely isn't the right answer, but can you try this again in like 26 minutes?

**Review by adurso3 — APPROVED** [review]

**Pull request merged**
